//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Administrative.rc
//
#define IDD_ABOUTBOX                    100
#define ID_VIEW_ARRANGE                 127
#define IDI_OWNER                       130
#define IDI_LICENSE                     133
#define IDI_STATION                     136
#define IDI_MOBILE                      137
#define IDI_SMS4DC                      141
#define IDI_SMS                         141
#define IDI_EQUIPMENT                   142
#define IDI_FREQUENCY                   143
#define IDI_INVOICE                     145
#define IDD_GRID                        146
#define IDI_BC                          148
#define IDI_ANTENNA                     149
#define IDI_PAYMENT                     150
#define IDI_FEE                         151
#define IDI_SAVE                        152
#define IDD_PAYMENT                     154
#define IDD_NOTICE                      155
#define IDD_EQ_CAT                      156
#define IDI_RECEIVER                    158
#define IDD_ADD_RECEIVER                160
#define IDI_UNLICENSED                  162
#define IDD_ANT_PATTERN                 163
#define IDD_MOVE_STATION                164
#define IDD_TxRxFilterDLG               165
#define IDI_ACTIVE                      166
#define IDI_INACTIVE                    167
#define IDD_AuditTrail                  169
#define IDI_GROUP                       171
#define IDD_GrpDetails                  172
#define IDB_ADD3                        176
#define IDB_ADD1                        177
#define IDB_ADD2                        178
#define IDB_SAVE3                       179
#define IDB_DELETE1                     180
#define IDB_DELETE2                     181
#define IDB_DELETE3                     182
#define IDB_FIRST1                      183
#define IDB_FIRST2                      184
#define IDB_FIRST3                      185
#define IDB_LAST1                       186
#define IDB_LAST2                       187
#define IDB_LAST3                       188
#define IDB_MINUS2                      189
#define IDB_MINUS3                      190
#define IDB_NEXT1                       191
#define IDB_NEXT2                       192
#define IDB_NEXT3                       193
#define IDB_PLUS2                       195
#define IDB_PLUS3                       196
#define IDB_PREV1                       197
#define IDB_PREV3                       198
#define IDR_GROUP_MENU                  199
#define IDB_SAVE1                       200
#define IDB_SAVE2                       201
#define IDB_PLUS1                       203
#define IDB_MINUS1                      204
#define IDR_ES_MENU                     205
#define IDD_ES_ANT_PAT                  206
#define IDD_SRS_NOTICE                  208
#define IDI_ALLOTMENT                   211
#define IDI_CONTOUR                     212
#define IDC_GRID                        1000
#define IDC_PROVISION                   1001
#define IDC_EDITBOX                     1002
#define IDC_PAYMENT_NO                  1003
#define IDC_SAVE_BUTTON                 1004
#define IDC_ATTACH                      1005
#define IDC_COMBO1                      1006
#define IDC_GRID_TITLE                  1007
#define IDC_COMBO2                      1008
#define IDC_COMBO3                      1009
#define IDC_COMBO4                      1010
#define IDC_COMBO5                      1011
#define IDC_COMBO6                      1012
#define IDC_DATEPICKER                  1013
#define IDC_TIMEPICKER                  1014
#define IDC_EDIT_BUTTON                 1015
#define IDC_CANCEL_BUTTON               1016
#define IDC_PAYMENT_VAL                 1017
#define IDC_ANTENNA                     1017
#define IDC_NOTICE_DATE                 1018
#define IDC_COMBO8                      1018
#define IDC_ACTION                      1019
#define IDC_COMBO9                      1019
#define IDC_MSHFLEXGRID1                1020
#define IDC_COMBO10                     1020
#define IDC_RESUB                       1020
#define IDC_POINT                       1021
#define IDC_PUBREQ                      1021
#define IDC_MULTIPOINT                  1022
#define IDC_PAY_DATE                    1023
#define IDC_ZONE_LIST                   1023
#define IDC_CIRCLE                      1024
#define IDC_RECEIVER_STATIONS           1025
#define IDC_CEN_LAT                     1026
#define IDC_CEN_LON                     1027
#define IDC_REC_RADIUS                  1028
#define IDC_HOP_ID                      1029
#define IDC_LINK_ID                     1030
#define IDC_LAT2                        1031
#define IDC_LON2                        1032
#define IDC_LAT3                        1033
#define IDC_LON3                        1034
#define IDC_LAT4                        1035
#define IDC_LON4                        1036
#define IDC_LAT5                        1037
#define IDC_LON5                        1038
#define IDC_LAT6                        1039
#define IDC_LON6                        1040
#define IDC_LAT1                        1041
#define IDC_LON1                        1042
#define IDC_TX_ANTENNA                  1043
#define IDC_NOISE_TEMP                  1044
#define IDC_EDIT_Channelsep             1045
#define IDC_ZONE                        1045
#define IDC_COMBO_fu                    1046
#define IDC_BUTTON_Draw                 1047
#define IDC_PAYMENT_DESC                1048
#define IDC_COMBO7                      1049
#define IDC_STATIONS                    1050
#define IDC_T14                         1051
#define IDC_AuditGrid                   1052
#define IDC_UserName                    1053
#define IDC_Table                       1054
#define IDC_AuditRefresh                1055
#define IDC_NORMALEDIT                  1056
#define IDC_ADDREC                      1057
#define IDC_DELREC                      1058
#define IDC_ESAntPatt                   1058
#define IDC_PATTERN                     1059
#define IDC_COEFF                       1060
#define IDC_CoeffA                      1061
#define IDC_CoeffB                      1062
#define IDC_AddPattern                  1062
#define IDC_SAVE                        1063
#define IDC_CoeffC                      1063
#define IDC_CoeffD                      1064
#define IDC_Phi1                        1065
#define IDC_NTC_ID                      1069
#define IDC_NTC_ID_lbl                  1070
#define IDC_NTC_TYPE_lbl                1071
#define IDC_NTC_TYPE                    1072
#define IDC_NTC_REFID_lbl               1073
#define IDC_NTC_REFID                   1074
#define IDC_NTC_DATE_lbl                1075
#define IDC_NTC_DATE                    1076
#define IDC_NTC_PROV_lbl                1077
#define IDC_NTC_ACTION_lbl              1079
#define IDC_NTC_ACTION                  1080
#define IDC_NTC_ADM_lbl                 1081
#define IDC_ER                          1081
#define IDC_NTC_ADM                     1082
#define IDC_NTC_SUB_lbl                 1083
#define IDC_NTC_SUB                     1084
#define IDC_NTC_PROV                    1085
#define IDC_ANT_LIST                    1086
#define IDC_NTC_RR_lbl                  1087
#define IDC_NTC_RR                      1088
#define IDC_NTC_TGTNTC_lbl              1089
#define IDC_POINTS                      1089
#define IDC_NTC_TGTNTC                  1090
#define IDC_H_PATTERN                   1090
#define IDC_V_PATTERN                   1091
#define IDR_ANTENNA_MENU                25000
#define IDR_BILLING_MENU                25001
#define IDR_EQUIPMENT_MENU              25002
#define IDR_FREQUENCY_MENU              25003
#define IDR_LICENSE_MENU                25004
#define IDR_MAINFRAME2                  25005
#define IDR_OWNER_MENU                  25006
#define IDR_RECEIVER_MENU               25007
#define IDR_STATION_MENU                25008
#define IDR_MAINFRAME                   25009
#define ID_EDITANTENNA                  25010
#define ID_DELETEANTENNA                25011
#define ID_COPYANTENNA                  25012
#define ID_ANTENNA_PATTERN              25013
#define ID_ADDINVOICE                   25014
#define ID_ADDPAYMENT                   25015
#define ID_EDITEQUIPMENT                25016
#define ID_DELETEEQUIPMENT              25017
#define ID_COPYEQUIPMENT                25018
#define ID_ADDANTENNA                   25019
#define ID_ADDFREQUENCY                 25020
#define ID_EDITFREQUENCY                25021
#define ID_DELETEFREQUENCY              25022
#define ID_COPYFREQUENCY                25023
#define ID_FREQUENCY_FILTERTX           25024
#define ID_FREQUENCY_FILTERRX           25025
#define ID_EDITLICENSE                  25026
#define ID_DELETELICENSE                25027
#define ID_COPYLICENSE                  25028
#define ID_CANCELLIC                    25029
#define ID_ADD_FX                       25030
#define ID_ADD_BC                       25031
#define ID_ADD_LM                       25032
#define ID_ADD_ML                       25033
#define ID_IMPORT_TECH                  25034
#define ID_LICENSE_PRINTLICENSE         25035
#define ID_LICENSE_PRINTSUMMARY         25036
#define ID_EDITOWNER                    25037
#define ID_DELETEOWNER                  25038
#define ID_ADDLICENSE                   25039
#define IDR_TREEVITYPE                  25040
#define ID_ADDOWNER                     25041
#define IDI_ESTATION                    25041
#define IDR_ESANT_MENU                  25041
#define ID_GRID_SAVE                    25042
#define IDI_EANTUP                      25042
#define IDR_CONTOUR_MENU                25042
#define ID_EDITSTATION                  25043
#define IDI_EANTDN                      25043
#define IDR_ALLOT_MENU                  25043
#define ID_DELETESTATION                25044
#define ID_COPYSTATION                  25045
#define ID_STATION_NOTICE               25046
#define ID_ADDEQUIPMENT                 25047
#define ID_LICENSE_NOTICE               25048
#define ID_DELETE_RECEIVER              25049
#define ID_REF_TABLES                   25050
#define ID_LICENSE_COPYTOARCHIVE        32821
#define ID_GROUP_FREQUENCY              32824
#define ID_GROUP_SPECIALSECTION         32825
#define ID_GROUP_COORDINATION           32826
#define ID_GROUP_FILTER                 32827
#define ID_ADDBEAMUP                    32828
#define ID_ADDBEAMDOWN                  32829
#define ID_GROUP_CLASSOFSTATION         32830
#define ID_EARTHSTATION_HORIZONTALELEVATION 32831
#define ID_EARTHSTATION_MINIMUMELEVANGLES 32832
#define ID_ADD_ES                       32833
#define ID_ADDGROUP                     32834
#define ID_GROUP_DELETE                 32835
#define ID_ESANTENNA_DELETE             32836
#define ID_EARTHSTATION_DELETE          32837
#define ID_EARTHSTATION_NOTICE          32838
#define ID_FREQUENCY_COORDINATION       32839
#define ID_ESANTENNA_SHOWPATTERN        32840
#define ID_EDITCONTOUR                  32841
#define ID_DELETECONTOUR                32842
#define ID_CONTOUR_POINTS               32843
#define ID_DELETEALLOT                  32846
#define ID_ATTACHCONTOUR                32848
#define ID_ALLOTMENT_ELECTRONICNOTICE   32849
#define ID_LICENSE_ADDALLOTMENT         32850
#define ID_LICENSE_MOVEALLOTMENT        32851
#define ID_FREQUENCY_SERVICEAREA        32852
#define ID_ALLOT_COORDINATION           32853
#define ID_CONTOUR_ELECTRONICNOTICE     32854
#define ID_DELETESELECTION              32855
#define ID_ADD_ALLOTMENT                40000
#define ID_EDITALLOT                    40001
#define ID_GROUP_EMISSIONS              40002
#define ID_TREE_REFRESH                 40003
#define ID_ADDCONTOUR                   40004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        214
#define _APS_NEXT_COMMAND_VALUE         32856
#define _APS_NEXT_CONTROL_VALUE         1092
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
